import type { ApiErrorMessages } from './nl'

export default {
  tab_not_found: 'Bill not found',
  tab_not_open: 'The bill is no longer open',
  tab_payment_pending: 'A payment is in progress for this bill',
  tab_payment_already_pending: 'A payment is already in progress for this bill',
  tab_changed: 'The bill has changed, reload and try again',
  tab_nothing_to_pay: 'Nothing to pay on this bill',
  tab_not_empty: 'Only an empty bill can be cancelled — cancel the lines first',
  split_too_small: 'Too little open to split like that',
  unknown_event: 'Unknown event — choose it again in the till’s settings',
  unknown_catalog: 'Unknown or archived menu',
  product_not_on_catalog: 'This product is not (or no longer) on the menu — reload the till',
  line_not_found: 'Line not found',
  nothing_to_void: 'Nothing left to cancel on this line',
  void_units_paid: 'These items are already paid — they can no longer be cancelled',
  void_exceeds_outstanding: 'Part has already been paid — cancelling would refund more than is still open',
  category_not_found: 'Category not found',
  category_in_use: 'This category is still used by products',
  unknown_category: 'Unknown category',
  station_not_found: 'Station not found',
  station_in_use: 'This station is still used by products',
  station_name_taken: 'A station with that name already exists',
  unknown_station: 'Unknown station',
  product_not_found: 'Product not found',
  unknown_product: 'Unknown or archived product',
  variant_not_found: 'Variant not found',
  last_active_variant: 'A product needs at least one active variant — archive the product instead',
  code_in_use: 'This code is already in use',
  product_code_taken: 'A code of this product is now used by another product',
  catalog_not_found: 'Menu not found',
  no_catalog: 'No menu found',
  default_catalog_not_archivable: 'The default menu cannot be archived — make another one the default first',
  catalog_layout_changed: 'The layout has changed in the meantime — reload and try again',
  section_not_found: 'Group not found',
  unknown_section: 'Unknown group for this menu',
  product_already_on_catalog: 'This product is already on this menu',
  import_too_many_rows: 'At most {max} rows per file',
  import_changed: 'Something changed in the meantime (e.g. a code is already in use) — make a new preview',
  import_group_missing: 'Group missing (and no row above to take it from)',
  import_product_missing: 'Product missing (and no row above to take it from)',
  import_too_long: '{field} is too long (max {max} characters)',
  import_price_negative: 'Price must be 0 or more',
  import_price_too_high: 'Price is too high (max € 10.000)',
  import_price_missing: 'Price missing',
  import_price_invalid: 'Price "{value}" is not a valid amount',
  import_vat_not_a_number: 'VAT "{value}" is not a number',
  import_vat_unknown: 'VAT {value}% does not exist — use {allowed}',
  import_quick_invalid: 'Quick buttons "{value}" — use whole numbers between 1 and 999, e.g. 5, 10, 20 (max 10)',
  import_visible_invalid: 'Visible "{value}" — use ja or nee',
  import_category_conflict: '{product}: a different category ("{value}") than on row {otherRow} ("{otherValue}") — rows {otherRow} and {row}',
  import_station_conflict: '{product}: a different station ("{value}") than on row {otherRow} ("{otherValue}") — rows {otherRow} and {row}',
  import_vat_conflict: '{product}: a different VAT rate ({value}) than on row {otherRow} ({otherValue}) — rows {otherRow} and {row}',
  import_duplicate_variant: '{name} is already on row {otherRow}',
  import_duplicate_code: 'Code "{code}" is already on row {otherRow}',
  import_code_other_product: 'Code "{code}" belongs to product "{owner}", not to "{product}" (which already exists separately)',
  import_same_existing_product: '"{product}" and "{other}" refer to the same existing product "{existing}"',
  import_code_in_use: 'Code "{code}" is already used by another product',
  import_variant_claimed: 'This variant is already on row {otherRow}',
  org_not_found: 'Organisation not found',
  not_instance_admin: 'Only this installation’s administrators can create or import an organisation',
  org_creation_disabled: 'New organisations cannot be created on this installation',
  demo_limit_reached: 'Too many demos are running at once — please try again in a while',
  not_an_export: 'This is not an Arcanum export file',
  export_version_unsupported: 'Export version {version} is not supported (expected {expected})',
  org_name_required: 'The organisation needs a name (max 100 characters)',
  import_invalid_count: 'Invalid count for {table}',
  not_importing: 'This organisation is not (or no longer) being imported',
  import_unknown_table: 'Unknown table',
  import_too_many_chunk_rows: 'At most {max} rows per chunk',
  import_not_abortable: 'Only an unfinished import can be cancelled',
  mail_not_configured: 'No email configuration found (and no platform default either)',
  mail_send_failed: 'Sending failed',
  invalid_email: 'That isn’t a valid email address',
  too_many_test_mails: 'Too many test emails — try again in an hour',
  bancontact_not_configured: 'Bancontact is not configured for this organisation',
  sumup_readers_failed: 'Could not fetch the SumUp readers',
  sumup_not_configured: 'SumUp isn’t set up for this organisation',
  sumup_pairing_code_invalid: 'A pairing code is 8 or 9 letters and digits',
  sumup_pair_failed: 'Pairing the reader failed',
  sumup_remove_failed: 'Unpairing the reader failed',
  device_name_required: 'Give the device a name',
  device_not_found: 'This device is not (or no longer) paired with this organisation',
  pairing_code_invalid: 'This pairing code is wrong, already used or expired — ask an admin for a new one',
  pairing_too_many_attempts: 'Too many wrong pairing codes — try again in 10 minutes',
  pairing_not_member: 'You’re not a member of this pairing code’s organisation — sign in with the right account',
  devicehub_failed: 'Devices are briefly unreachable — try again',
} satisfies ApiErrorMessages
