import type { ApiErrorMessages } from './nl'

export default {
  tab_not_found: 'Addition introuvable',
  tab_not_open: 'L’addition n’est plus ouverte',
  tab_payment_pending: 'Un paiement est en cours pour cette addition',
  tab_payment_already_pending: 'Un paiement est déjà en cours pour cette addition',
  tab_changed: 'L’addition a été modifiée, rechargez et réessayez',
  tab_nothing_to_pay: 'Rien à payer sur cette addition',
  tab_not_empty: 'Seule une addition vide peut être annulée — annulez d’abord les lignes',
  split_too_small: 'Trop peu ouvert pour partager ainsi',
  unknown_event: 'Événement inconnu — choisissez-le à nouveau dans les paramètres de la caisse',
  unknown_catalog: 'Carte inconnue ou archivée',
  product_not_on_catalog: 'Ce produit n’est (plus) sur la carte — rechargez la caisse',
  line_not_found: 'Ligne introuvable',
  nothing_to_void: 'Plus rien à annuler sur cette ligne',
  void_units_paid: 'Ces pièces sont déjà payées — elles ne peuvent plus être annulées',
  void_exceeds_outstanding: 'Une partie est déjà payée — annuler rembourserait plus que ce qui reste ouvert',
  category_not_found: 'Catégorie introuvable',
  category_in_use: 'Cette catégorie est encore utilisée par des produits',
  unknown_category: 'Catégorie inconnue',
  station_not_found: 'Poste introuvable',
  station_in_use: 'Ce poste est encore utilisé par des produits',
  station_name_taken: 'Un poste de ce nom existe déjà',
  unknown_station: 'Poste inconnu',
  product_not_found: 'Produit introuvable',
  unknown_product: 'Produit inconnu ou archivé',
  variant_not_found: 'Variante introuvable',
  last_active_variant: 'Un produit a besoin d’au moins une variante active — archivez plutôt le produit',
  code_in_use: 'Ce code est déjà utilisé',
  product_code_taken: 'Un code de ce produit est entre-temps utilisé par un autre produit',
  catalog_not_found: 'Carte introuvable',
  no_catalog: 'Aucune carte trouvée',
  default_catalog_not_archivable: 'La carte par défaut ne peut pas être archivée — choisissez d’abord une autre carte par défaut',
  catalog_layout_changed: 'La mise en page a été modifiée entre-temps — rechargez et réessayez',
  section_not_found: 'Groupe introuvable',
  unknown_section: 'Groupe inconnu pour cette carte',
  product_already_on_catalog: 'Ce produit est déjà sur cette carte',
  import_too_many_rows: 'Maximum {max} lignes par fichier',
  import_changed: 'Quelque chose a changé entre-temps (p. ex. un code est déjà utilisé) — refaites un aperçu',
  import_group_missing: 'Groupe manquant (et aucune ligne au-dessus dont le reprendre)',
  import_product_missing: 'Produit manquant (et aucune ligne au-dessus dont le reprendre)',
  import_too_long: '{field} est trop long (max {max} caractères)',
  import_price_negative: 'Le prix doit être de 0 ou plus',
  import_price_too_high: 'Le prix est trop élevé (max € 10.000)',
  import_price_missing: 'Prix manquant',
  import_price_invalid: 'Le prix « {value} » n’est pas un montant valable',
  import_vat_not_a_number: 'La TVA « {value} » n’est pas un nombre',
  import_vat_unknown: 'La TVA {value} % n’existe pas — utilisez {allowed}',
  import_quick_invalid: 'Boutons rapides « {value} » — utilisez des nombres entiers entre 1 et 999, p. ex. 5, 10, 20 (max 10)',
  import_visible_invalid: 'Visible « {value} » — utilisez ja ou nee',
  import_category_conflict: '{product} : autre catégorie (« {value} ») qu’à la ligne {otherRow} (« {otherValue} ») — lignes {otherRow} et {row}',
  import_station_conflict: '{product} : autre poste (« {value} ») qu’à la ligne {otherRow} (« {otherValue} ») — lignes {otherRow} et {row}',
  import_vat_conflict: '{product} : autre taux de TVA ({value}) qu’à la ligne {otherRow} ({otherValue}) — lignes {otherRow} et {row}',
  import_duplicate_variant: '{name} figure déjà à la ligne {otherRow}',
  import_duplicate_code: 'Le code « {code} » figure déjà à la ligne {otherRow}',
  import_code_other_product: 'Le code « {code} » appartient au produit « {owner} », pas à « {product} » (qui existe déjà séparément)',
  import_same_existing_product: '« {product} » et « {other} » renvoient au même produit existant « {existing} »',
  import_code_in_use: 'Le code « {code} » est déjà utilisé par un autre produit',
  import_variant_claimed: 'Cette variante figure déjà à la ligne {otherRow}',
  org_not_found: 'Organisation introuvable',
  not_instance_admin: 'Seuls les administrateurs de cette installation peuvent créer ou importer une organisation',
  org_creation_disabled: 'Impossible de créer de nouvelles organisations sur cette installation',
  demo_limit_reached: 'Trop de démos en cours en même temps — réessayez dans un moment',
  not_an_export: 'Ce n’est pas un fichier d’exportation Arcanum',
  export_version_unsupported: 'La version d’exportation {version} n’est pas prise en charge (attendu : {expected})',
  org_name_required: 'L’organisation a besoin d’un nom (max 100 caractères)',
  import_invalid_count: 'Nombre invalide pour {table}',
  not_importing: 'Cette organisation n’est pas (plus) en cours d’importation',
  import_unknown_table: 'Table inconnue',
  import_too_many_chunk_rows: 'Maximum {max} lignes par morceau',
  import_not_abortable: 'Seule une importation inachevée peut être annulée',
  mail_not_configured: 'Aucune configuration e-mail trouvée (ni de valeur par défaut de la plateforme)',
  mail_send_failed: 'L’envoi a échoué',
  invalid_email: 'Ce n’est pas une adresse e-mail valide',
  too_many_test_mails: 'Trop d’e-mails de test — réessayez dans une heure',
  bancontact_not_configured: 'Bancontact n’est pas configuré pour cette organisation',
  sumup_readers_failed: 'Impossible de récupérer les lecteurs SumUp',
  sumup_not_configured: 'SumUp n’est pas configuré pour cette organisation',
  sumup_pairing_code_invalid: 'Un code de couplage compte 8 ou 9 lettres et chiffres',
  sumup_pair_failed: 'Le couplage du lecteur a échoué',
  sumup_remove_failed: 'Le découplage du lecteur a échoué',
  device_name_required: 'Donnez un nom à l’appareil',
  device_not_found: 'Cet appareil n’est (plus) couplé à cette organisation',
  pairing_code_invalid: 'Ce code de couplage est incorrect, déjà utilisé ou expiré — demandez-en un nouveau à un administrateur',
  pairing_too_many_attempts: 'Trop de codes de couplage erronés — réessayez dans 10 minutes',
  pairing_not_member: 'Vous n’êtes pas membre de l’organisation de ce code de couplage — connectez-vous avec le bon compte',
  devicehub_failed: 'Les appareils sont momentanément injoignables — réessayez',
} satisfies ApiErrorMessages
