// arcanum-backend's user-facing error codes (src/errors.ts there) — nl is
// the backend's own Dutch text, verbatim; fr.ts/en.ts must have every code
// with the same {placeholders} (see api-errors.test.ts).
const nl = {
  tab_not_found: 'Rekening niet gevonden',
  tab_not_open: 'Rekening is niet meer open',
  tab_payment_pending: 'Er loopt een betaling voor deze rekening',
  tab_payment_already_pending: 'Er loopt al een betaling voor deze rekening',
  tab_changed: 'Rekening is gewijzigd, herlaad en probeer opnieuw',
  tab_nothing_to_pay: 'Niets te betalen op deze rekening',
  tab_not_empty: 'Alleen een lege rekening kan geannuleerd worden — annuleer eerst de lijnen',
  split_too_small: 'Te weinig open om zo te verdelen',
  unknown_event: 'Onbekend evenement — kies het opnieuw in de instellingen van de kassa',
  unknown_catalog: 'Onbekende of gearchiveerde menukaart',
  product_not_on_catalog: 'Dit product staat niet (meer) op de menukaart — herlaad de kassa',
  line_not_found: 'Lijn niet gevonden',
  nothing_to_void: 'Niets meer te annuleren op deze lijn',
  void_units_paid: 'Deze stuks zijn al betaald — ze kunnen niet meer geannuleerd worden',
  void_exceeds_outstanding: 'Er is al een deel betaald — annuleren zou meer terugbetalen dan er open staat',
  category_not_found: 'Categorie niet gevonden',
  category_in_use: 'Deze categorie wordt nog gebruikt door producten',
  unknown_category: 'Onbekende categorie',
  station_not_found: 'Station niet gevonden',
  station_in_use: 'Dit station wordt nog gebruikt door producten',
  station_name_taken: 'Er bestaat al een station met die naam',
  unknown_station: 'Onbekend station',
  product_not_found: 'Product niet gevonden',
  unknown_product: 'Onbekend of gearchiveerd product',
  variant_not_found: 'Variant niet gevonden',
  last_active_variant: 'Een product heeft minstens één actieve variant nodig — archiveer dan het product',
  code_in_use: 'Deze code wordt al gebruikt',
  product_code_taken: 'Een code van dit product wordt intussen door een ander product gebruikt',
  catalog_not_found: 'Menukaart niet gevonden',
  no_catalog: 'Geen menukaart gevonden',
  default_catalog_not_archivable: 'De standaardmenukaart kan niet gearchiveerd worden — maak eerst een andere standaard',
  catalog_layout_changed: 'De indeling is intussen gewijzigd — herlaad en probeer opnieuw',
  section_not_found: 'Groep niet gevonden',
  unknown_section: 'Onbekende groep voor deze menukaart',
  product_already_on_catalog: 'Dit product staat al op deze menukaart',
  import_too_many_rows: 'Maximaal {max} rijen per bestand',
  import_changed: 'Er is intussen iets gewijzigd (bv. een code wordt al gebruikt) — maak opnieuw een voorbeeld',
  import_group_missing: 'Groep ontbreekt (en er is geen rij erboven om van over te nemen)',
  import_product_missing: 'Product ontbreekt (en er is geen rij erboven om van over te nemen)',
  import_too_long: '{field} is te lang (max {max} tekens)',
  import_price_negative: 'Prijs moet 0 of meer zijn',
  import_price_too_high: 'Prijs is te hoog (max € 10.000)',
  import_price_missing: 'Prijs ontbreekt',
  import_price_invalid: 'Prijs "{value}" is geen geldig bedrag',
  import_vat_not_a_number: 'BTW "{value}" is geen getal',
  import_vat_unknown: 'BTW {value}% bestaat niet — gebruik {allowed}',
  import_quick_invalid: 'Snelknoppen "{value}" — gebruik hele getallen tussen 1 en 999, bv. 5, 10, 20 (max 10)',
  import_visible_invalid: 'Zichtbaar "{value}" — gebruik ja of nee',
  import_category_conflict: '{product}: andere categorie ("{value}") dan op rij {otherRow} ("{otherValue}") — rijen {otherRow} en {row}',
  import_station_conflict: '{product}: ander station ("{value}") dan op rij {otherRow} ("{otherValue}") — rijen {otherRow} en {row}',
  import_vat_conflict: '{product}: ander BTW-tarief ({value}) dan op rij {otherRow} ({otherValue}) — rijen {otherRow} en {row}',
  import_duplicate_variant: '{name} staat al op rij {otherRow}',
  import_duplicate_code: 'Code "{code}" staat al op rij {otherRow}',
  import_code_other_product: 'Code "{code}" hoort bij product "{owner}", niet bij "{product}" (dat bestaat al apart)',
  import_same_existing_product: '"{product}" en "{other}" verwijzen naar hetzelfde bestaande product "{existing}"',
  import_code_in_use: 'Code "{code}" is al in gebruik bij een ander product',
  import_variant_claimed: 'Deze variant staat al op rij {otherRow}',
  org_not_found: 'Organisatie niet gevonden',
  not_instance_admin: 'Alleen de beheerders van deze installatie kunnen een organisatie aanmaken of importeren',
  not_an_export: 'Dit is geen Arcanum-exportbestand',
  export_version_unsupported: 'Exportversie {version} wordt niet ondersteund (verwacht {expected})',
  org_name_required: 'De organisatie heeft een naam nodig (max 100 tekens)',
  import_invalid_count: 'Ongeldig aantal voor {table}',
  not_importing: 'Deze organisatie wordt niet (meer) geïmporteerd',
  import_unknown_table: 'Onbekende tabel',
  import_too_many_chunk_rows: 'Maximaal {max} rijen per stuk',
  import_not_abortable: 'Alleen een onafgewerkte import kan geannuleerd worden',
  invalid_domain: 'Vul een geldige domeinnaam in (bv. pos.mijnorganisatie.be)',
  domain_requires_idp: 'Configureer eerst een eigen identity provider voor deze organisatie (zie Aanmelding) voordat je een aangepast domein instelt.',
  domain_in_use: 'Dit domein is al in gebruik door een andere organisatie',
  domain_registration_failed: 'Kon domein niet registreren bij Cloudflare',
  domain_status_failed: 'Kon status niet ophalen bij Cloudflare',
  domain_routing_failed: 'Kon geen routing instellen voor dit domein bij Cloudflare',
  idp_discovery_failed: 'Kon de issuer-URL niet bereiken, of deze ondersteunt geen apparaatcode-aanmelding (vereist voor de kassa-toestellen).',
  mail_not_configured: 'Geen e-mailconfiguratie gevonden (en ook geen platform-standaard)',
  mail_send_failed: 'Verzenden mislukt',
  bancontact_not_configured: 'Bancontact niet geconfigureerd voor deze organisatie',
  sumup_readers_failed: 'Kon SumUp readers niet ophalen',
}

export type ApiErrorCode = keyof typeof nl
export type ApiErrorMessages = Record<ApiErrorCode, string>
export default nl
